# Base configs
baseurl: "https://dinogura.pictures"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "dinogura.pictures"
subtitle: "Cute Photos of #dinogura"
author: "Moe Chinatsu"
header:
 title: "[dinogura.pictures]"
 subtitle: "Cute Photos of #dinogura"
footer:
 name: "dinogura.pictures "
 bio: "Fan account of Gawr Gura. Sharing cute photo of #dinogura. New post every Monday and Wednesday⁣"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/dinogura_pics"
  instagram: "https://www.instagram.com/dinogura.pictures"
